#!/bin/bash

# Define the mapping of OIDs to IPs
declare -A OID_IP_MAP
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.1"]="3.0.52.254" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.2"]="10.147.84.18" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.3"]="10.147.84.12" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.4"]="10.147.84.18" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.5"]="10.147.84.29" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.6"]="10.147.90.12" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.7"]="10.147.90.13"
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.28"]="10.147.84.31" 
OID_IP_MAP[".1.3.6.1.4.1.33744.2.1.4.29"]="10.147.90.13" 

# Function to check if an IP is reachable
ping_ip() {
    ping -c 1 -W 1 $1 > /dev/null 2>&1
    return $?
}

# Check if the first argument is -g
if [ "$1" = "-g" ]; then
    OID=$2  # The OID provided in the second argument

    # Check if the OID exists in the mapping
    if [[ -n "${OID_IP_MAP[$OID]}" ]]; then
        # Get the corresponding IP for the OID
        IP=${OID_IP_MAP[$OID]}

        # Ping the IP address
        ping_ip $IP

        if [ $? -eq 0 ]; then
            echo "$2" 
            echo "integer" 
            echo "0" 
        else
            echo "$2" 
            echo "integer" 
            echo "1" 
        fi
    else
        echo "Invalid OID" 
    fi
fi
